MEM_STATES = "states"
MEM_PARTIAL_PLAN = "partial plan"
MEM_PLANS = "plans"
MEM_CURRENT_PLAN = "current plan"
MEM_OLD_PLANS = "old plans"
MEM_ACTIONS = "actions"
MEM_ADIST = "aDist"
MEM_ANOM = "anomalous"
MEM_NODES = "gngNodes"
MEM_ANOM_TYPE = "anomType"
MEM_USER_GOALS = "predefined goals"
MEM_GOALS = "goals"
MEM_CUR_GOALS = "current goals"
MEM_GOAL_COMPLETED = "current goal achieved"
MEM_VALENCE = "valence"

SOCKET_R = "read socket"
SOCKET_W = "write socket"
